server:
  port: 8081

spring:
  application:
    name: transaction-service

  # H2 Database for local testing (no PostgreSQL required)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  # Disable Eureka for local testing
  cloud:
    discovery:
      enabled: false

eureka:
  client:
    enabled: false

# Simple Redis configuration
spring.redis:
  host: localhost
  port: 6379
  timeout: 10000

# Disable Redisson for local testing if Redis not available
redisson:
  enabled: false

# Circuit Breaker - simplified for local
resilience4j:
  circuitbreaker:
    instances:
      transaction-processing:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        minimum-number-of-calls: 5

# Logging
logging:
  level:
    root: INFO
    com.transactionengine: DEBUG